version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Npm Installing"
      - run: npm install
      - run: npm run build

  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Double Trouble"
      - run: npm install
      - run: npm test

  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hi There!!"

workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
